### ISSUE TITLE
【平衡讨论】霜冻巨人

### ISSUE THREAD

**Issue by newhandapo** [neal2018/LegacyGwent#13]
霜冻巨人 食人魔 8战力
场上每有一个“刺骨冰霜“灾厄效果，便获得3点增益。每有一个“刺骨冰霜“灾厄效果出现在场上，便获得3点增益。

**Comment by neal2018** [comment]
已实装，后续bug可以在本issue报告

**Comment by fraloow** [comment]
描述修改：
场上每有一道“刺骨冰霜”或**同排**出现“刺骨冰霜”时，便获得3点增益
代码修改：
同排重叠打霜不执行增益
