### ISSUE TITLE
【平衡讨论】绞盘

### ISSUE THREAD

**Issue by newhandapo** [neal2018/LegacyGwent#14]
绞盘：择一：从己方墓场中打出 1 张铜色北方领域“机械”牌，并使其获得佚亡。或所有己方机械+3增益。

**Comment by neal2018** [comment]
已装

实装效果：

绞盘：择一：从己方墓场中打出 1 张铜色~~北方领域~~“机械”牌，并使其获得佚亡。或所有己方机械+3增益。

懒得加阵营限制
