### ISSUE TITLE
【新卡讨论】【fraloow】沃米尔

### ISSUE THREAD

**Issue by fraloow** [neal2018/LegacyGwent#16]
**新卡描述**
<img src="https://user-images.githubusercontent.com/50948805/83935454-4893fd00-a7ec-11ea-9ea1-cb130b65376e.png" width="25%" height="25%">

卡名：沃米尔
品质：银卡
阵营：北方领域
类型：单位卡
标签：瑞达尼亚，军官
战力：8
效果：择一：选择一个单位将其增益转换为护甲；选择两个单位将其护甲转换为增益

设计者：@fraloow

设计者的想法：仅为护甲北提供一个新玩具，使其有更多的应对手段

**Comment by neal2018** [comment]
其实可以直接贴个原issue的link

**Comment by neal2018** [comment]
已装，感觉偏强

**Comment by fraloow** [comment]
可选的改动方案：
战力：8->7
效果：
择一：选择一个单位将其增益转换为护甲；选择两个单位将其护甲转换为增益
->
择一：选择一个单位将其增益转换为护甲**并削减一半的护甲**；选择两个单位将其护甲转换为增益
