### ISSUE TITLE
7月平衡补丁-实装到Neal服内测版本

### ISSUE THREAD

**Issue by RealAidenPearce** [neal2018/LegacyGwent#18]
[PTR PATCH NOTES 0706.pdf](https://github.com/neal2018/LegacyGwent/files/4879524/PTR.PATCH.NOTES.0706.pdf)

**Comment by neal2018** [comment]
黏贴一份到网页端

---
内部服 PTR 平衡补丁测试说明
BY 安度因
注：此平衡补丁为 PTR 测试内部使用，具体实装版本会在测试后确定。
一、怪兽
吸血鬼体系
暗影长者：领袖，3 战力，吸血鬼，将一个友军非“吸血鬼”单位变为“蝠翼魔”，随后汲
食所有未受伤的敌军单位 1 点战力。
注：是暗影长者汲食，不是蝠翼魔。
蝠魔：2 战力，吸血鬼，汲食一个敌方单位 3 点战力，若其未被摧毁，则自身变为“蝠翼魔”
的原始同名牌。
月光体系
猫人：3 战力，野兽，诅咒生物，每个回合结束时，若所在排有“满月”恩泽，对最弱的敌
方单位造成 3 点伤害。
女蛇妖：10 战力，野兽，若场上任意位置有“血月”，使 1 个友方“野兽”单位获得免疫。
注：修改了没有出场机会的月光体系单卡
狂猎体系
狂猎战士：9 战力，狂猎，将 1 个敌军单位上移一排，若该排上“刺骨冰霜”生效，则对其
造成 2 点伤害。
狂猎骑士：8 战力，狂猎，场上每有一个其他友方“狂猎单位”，获得 1 点增益。使对方同
排的“刺骨冰霜”伤害提升 1 点。
注：对两个狂猎单位进行了微调看看效果。
其他
戴维娜符文石：炼金，特殊，道具，使牌组中最弱的铜色“怪兽”单位获得 2 点增益，随后
打出它。
伊芙利特：8 战力，构造体，吞噬 1 个友方铜色/银色单位，然后变为其基础同名牌。
翼手龙：5 战力，龙兽，吞噬己方墓地中的 1 个铜色单位，并获得其战力的护甲。每个回合
结束时，对自身和同排最弱敌方单位分别造成 2 点伤害。
鹿首魔：13 战力，残物，对自身造成 7 点伤害，每有一个其他友方“怪兽”单位，则减少 1
点伤害。
远古小雾妖：食腐生物，回合结束时，若场上任意位置有“蔽日浓雾”，在自身右侧生成 1
个“小雾妖”的原始同名牌。
二、帝国
间谍体系
希拉德：3 战力，军官，魅惑 1 个战力不超过 8 点的“间谍”单位。
冒牌希里：11 战力，改变敌方打出的下 1 个单位的“间谍”状态。
大使：1 战力，间谍，生成 1 个敌方场上铜色单位的原始同名牌。
暗算：对 2 个敌军单位造成 4 点伤害，对方场上每存在 1 个“间谍”单位，伤害提升 1 点。
阿尔巴师
蒂博尔·艾格布拉杰：6 战力，军官，创造 1 个“阿尔巴师”单位，并使其获得 2 点护甲。
阿尔巴师枪兵：2 战力，士兵，召唤所有同名牌，若相邻单位均为“士兵”，则使所有同名
牌获得 1 点强化。
阿尔巴师装甲骑兵：6 战力，士兵，触发 1 个友方铜色“机械”单位的部署效果。操控。
阿尔巴师矛兵：10 战力，士兵，己方每打出 1 张“士兵”单位牌，使其获得 2 点护甲。
注：借爆牌删除的机会，尝试对阿尔巴师的单位进行重做。
帝国机械
射石机：添加“驱动：伤害提高 1 点”。
投尸机：添加“驱动：牛尸倒计时减少 1 回合”。
火蝎攻城弩：添加“驱动：若摧毁目标，则隐匿 1 张牌。”
作战工程师：5 战力，辅助，使一个 1 个友方机械获得 5 点增益，操控。
维尔海夫：5 战力，军官，生成 1 个尼弗迦德铜色“机械”单位。
注：我知道有人觉得帝国不应该使用与北方相同的机械体系，但我十分希望能看到他们改动
后的具体表现，对上述的阿尔巴师改动也一样，我希望能给这种设计一个测试的机会。同时，
目前正在尝试给帝国机械不一样的体系，以及考虑带回凛冬前的列阵关键词。
炼金体系
达兹伯格符文石：炼金，特殊，道具，创造 1 个银色“法师”单位，使其获得佚亡。
注：重申一遍，看三美女设计师不背锅。
吊死鬼之毒：炼金，特殊，道具，对一个单位造成 5 点伤害，若目标已受伤，则将其摧毁。
其他
叶奈法：死灵法师：6 战力，法师，从己方墓场复活 1 个铜色“士兵”单位。
沙斯西乌斯：13 战力，法师，择一：检视对方牌组顶的 3 张牌，将其中 1 张牌置于底端；
揭示对方手牌中所有最弱的单位牌。
三、北方
诅咒生物体系
雅妲：领袖，4 战力，诅咒生物，生成己方牌库中 1 个北方领域铜色/银色“诅咒生物”的 1
张佚亡基础同名牌。
染血连枷：道具，特殊，造成 5 点伤害，若摧毁目标，则在近战排生成 1 个科德温亡魂的原
始同名牌。
机械体系
福尔泰斯特之傲：8 战力 2 护甲，泰莫利亚，机械，对一个敌军单位造成 2 点伤害，并将其
上移一排。己方每打出 1 个“士兵”单位，再次触发此能力。驱动：伤害提升 1 点。
绞盘：谋略，特殊，择一；从己方墓场中打出 1 张铜色北方领域“机械”牌，并使其获得佚
亡；使所有友方机械单位获得 3 点增益。
泰莫利亚鼓手：6 战力，泰莫利亚，辅助，使一个友方非“机械”单位获得 3 点增益和操控。
其他
普希拉：8 战力，辅助，每个回合结束时，治愈最弱的友方单位。
佐李亚符文石：炼金，道具，特殊，创造 1 个铜色“北方领域”士兵单位，分别属于“泰莫
利亚”，“瑞达尼亚”，“科德温”，使其获得 3 点护甲。
欧德林：7 战力 3 护甲，科德温，士兵，回合开始时，移动至除所在排外己方单位最多的一
排，使同排所有友军单位获得 1 点增益。操控。
崔丹姆步兵：10 战力 4 护甲，士兵，回合结束时，若受护甲保护，使相邻友方单位获得 1
点护甲。
四、松鼠
伏击体系
莫丽恩：森林之女：10 战力，树精，重新盖伏 1 个已翻开的友方银色/铜色“伏击”单位。
麦莉：4 战力，精灵，伏击，当对方下次打出铜色/银色特殊牌时，翻开并抵消其能力。
私枭治疗者：6 战力，精灵，伏击，2 回合后的回合开始翻开，使同排友方单位获得 2 点增
益。
矮人体系
马哈坎志愿军：5 战力，矮人，力竭，回合结束时，若己方场上只有矮人单位，则从牌库召
唤 1 张同名牌，然后在牌库底端生成 1 张基础同名牌。
马哈坎守卫：4 战力，矮人，使一个友方单位获得 5 点增益，同排每有一个友方矮人单位，
增益提升 1 点。
马哈坎捍卫者：4 战力，矮人，坚韧，对方同排每有 1 个非“矮人”单位，强化自身 1 点战
力。
注：我们知道喜欢玩纯矮人的玩家不少，这里尝试调整了一下矮人卡组的长短局能力，希望
带来一些改变。
其他
菲拉凡德瑞：领袖，4 战力，精灵，生成友方场上 1 个银色“精灵”单位或铜色“松鼠党”
单位的基础同名牌。
注：伏击单位只有翻开后才能被选取。
萨奇亚萨斯：9 战力，亚甸，龙兽，对一个敌方单位造成 1 点伤害，然后使自身获得 1 点增
益。己方场上每有一个独特的标签，伤害与增益都各提升 1 点。
注：例如：精灵，矮人，龙兽，法师，士兵等，不计算自身。
莫拉纳符文石：检视己方牌组中随机铜色/银色“树精”、“精灵”、“矮人”各一张，然后选
择一张并打出。
五、群岛
图尔赛克家族
艾斯特图尔赛克：5 战力，领袖，图尔赛克家族，生成 1 个铜色/银色“图尔赛克家族”单
位。
图尔赛克家族好斗分子：6 战力，图尔赛克家族，士兵，在墓场中时，己方打出 1 个 “图
尔赛克家族”单位后，复活此单位至近战排并获得佚亡。
奎特家族
凯瑞斯：无所畏惧：10 战力，奎特家族，军官，免疫，在手牌或牌库中时，本局对战中你
每丢弃过 1 张牌，获得 1 点强化。
哈尔玛奎特：23 战力，奎特家族，军官，佚亡，在对方同排生成“乌德维克之主”，每个己
方回合结束时，若“乌德维克之主”未被摧毁，对自身造成 3 点削弱。
注：乌德维克之主，5 战力，遗愿：使哈尔玛奎特获得 10 点增益。
奎特家族劫掠者：3 战力，奎特家族，士兵，佚亡，将 1 个友方铜色非“诅咒生物”单位从
墓地返回牌库，对 1 个敌方单位造成等同于目标单位战力的伤害。
奎特家族战士：11 战力，奎特家族，士兵，对 1 个敌方单位造成 4 点伤害，若目标未被摧
毁，对自身也造成 4 点伤害。
德拉蒙家族
德拉蒙家族持盾女卫：3 战力，德拉蒙家族，士兵，被丢弃时，在己方牌库中生成 2 个自身
的原始同名牌。打出时，从牌组召唤所有同名卡至己方近战排。
迪门家族
朱塔迪门：4 战力，迪门家族，士兵，从己方牌库打出 1 个铜色史凯利格“机械”单位。
海玫家族
海玫家族诗人：8 战力，海玫家族，辅助，己方战场上每有 1 个其他“家族”的单位，获得
1 点增益。每次从手牌、战场、墓场返回己方卡组时，从牌组中丢弃最弱的单位。
呓语
韦博约恩：6 战力，诅咒生物，呓语，标记 1 个敌方单位，每个己方回合结束使其受到 2 点
伤害，直到其被摧毁。
大野猪：7 战力，野兽，诅咒生物，呓语，在己方回合受到伤害时，获得 2 点强化，在敌方
回合受到伤害时，对最弱的敌方单位造成 2 点伤害。
暴怒的狂战士：9 战力，诅咒生物，士兵，呓语，每个己方回合结束时，对自身和最强的敌
方单位造成 1 点伤害，当自身战力低于 5 点时，变为“恶熊”。
其他
华美的长剑：特殊，道具，生成 1 个己方手牌中铜色史凯利格“士兵”单位的原始同名牌，
并使其获得 2 点强化。
史崔伯格符文石：特殊，炼金，道具，若己方场上存在至少 2 个不同“家族”，从己方墓场
或牌库打出 1 个铜色/银色史凯利格“辅助”单位。
六、中立
杰洛特：猎魔大师：6 战力，猎魔人，对 1 个敌方单位造成 3 点伤害，若目标战力为奇数，
则改为直接将其摧毁。
阿瓦拉克：7 战力，法师，精灵，创造 1 张铜色/银色“灾厄”牌。
雷吉斯：高等吸血鬼：将铜色改为铜色/银色。
死灵术：法术，特殊，摧毁 1 个友方单位，随后从双方墓场复活 1 个铜色/银色非“间谍”
单位并使其获得佚亡。
杜度：1 战力，残物，变为己方手牌、牌库中 1 张铜色单位牌的基础同名牌，获得佚亡。
斯崔葛布：9 战力，法师，佚亡，将对方手牌中最强的非“间谍”单位牌战力降为 1。

**Comment by neal2018** [comment]
原始内容comment到了上一层，太长已折叠

**Comment by neal2018** [comment]
记得在https://github.com/neal2018/LegacyGwent/的DesignerServer下提PR

**Comment by RealAidenPearce** [comment]
7月6日 对大野猪的效果进行了修改 从名单中移除了远古小雾妖

**Comment by RealAidenPearce** [comment]
其中希望neal给较高优先度的是，看着好写的挑吧 这些上正式服都问题不大：
怪兽：暗影长者与蝠魔（吸血鬼体系补全） 狂猎战士 狂猎骑士（狂猎组件微调）
帝国：吊死鬼之毒 叶奈法：死灵法师
北方：福尔泰斯特之傲 绞盘（类似回滚）
松鼠：马哈坎志愿军 马哈坎守卫 马哈坎捍卫者（矮人体系的微调）
群岛：艾斯特图尔赛克（微调） 凯瑞斯：无所畏惧（重做） 大野猪（微调，添加词条）
中立：杜度 雷吉斯：高等吸血鬼（微调）
以及各势力的符文石
参考 PATCH NOTES 0706

**Comment by RealAidenPearce** [comment]
[PTR PATCH NOTES 0707.pdf](https://github.com/neal2018/LegacyGwent/files/4885149/PTR.PATCH.NOTES.0707.pdf)

**Comment by RealAidenPearce** [comment]
7月7日对名单进行了更新
